language: cpp
sudo: required
dist: trusty
compiler: 
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    env: COMPILER=g++-5
    
before_script:
  - utils/premake5_x64 gmake
  - cd Build

script: make CXX=g++-5 CC=gcc-5 config=release_x64
 
notifications:
  irc:
    channels:
      - "irc.gtanet.com#mta.dev"
    on_success: change
    on_failure: always
