language: cpp
compiler: 
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    env: COMPILER=g++-5
    
before_script:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha9/premake-5.0.0-alpha9-linux.tar.gz
  - tar xzf premake-5.0.0-alpha9-linux.tar.gz
  - ./premake gmake
  - cd Build

script: make -j 3 CXX=g++-5 CC=gcc-5 config=release_x64
 
notifications:
  irc:
    channels:
      - "irc.gtanet.com#mta.dev"
    on_success: never
    on_failure: never
