resources:
  containers:
  - container: ci
    image: sbx320/mtasa-blue-azure:latest

jobs:
- job: linux
  pool:
    vmImage: 'Ubuntu 16.04'
  container: ci
  steps:
  - script: ./linux-build.sh
    displayName: 'Run Build'
- job: windows
  pool:
    vmImage: 'VS2017-Win2016'
  variables:
    solution: 'Build/MTASA.sln'
    buildConfiguration: 'Release'
  steps:
  - powershell: Invoke-WebRequest https://mirror.mtasa.com/bdata/DXFiles.zip -OutFile utils/DXFiles.zip
    displayName: 'Download DirectX'

  - powershell: Expand-Archive -Path utils/DXFiles.zip -DestinationPath utils/DXFiles
    displayName: 'Extract DirectX'
  - script: utils\premake5 install_cef
    displayName: 'Install CEF'
  - script: utils\premake5 vs2017
    env:
      DXSDK_DIR: './utils/DXFiles/'
      CI: 'true'
    displayName: 'Create Visual Studio 2017 Solution'
  - script: utils\premake5 install_data
    displayName: 'Install data files'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      configuration: '$(buildConfiguration)'
 
  - script: utils\premake5 compose_files
    displayName: 'Create InstallFiles'
 
  # .zip appended to Destination automatically
  - powershell: Compress-Archive -Path InstallFiles -DestinationPath '$(Build.ArtifactStagingDirectory)/InstallFiles'
    displayName: 'Compress InstallFiles'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish InstallFiles.zip'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/InstallFiles.zip' 
      artifactName: 'InstallFiles.zip'
      #publishLocation: 'Container' # Options: container, filePath
      #targetPath: # Required when publishLocation == FilePath
      #parallel: false # Optional
      #parallelCount: # Optional

  - task: PublishBuildArtifacts@1
    displayName: 'Publish InstallFiles folder'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/InstallFiles' 
      artifactName: 'InstallFiles' 
      #publishLocation: 'Container' # Options: container, filePath
      #targetPath: # Required when publishLocation == FilePath
      #parallel: false # Optional
      #parallelCount: # Optional
