name: "Rebuild en_US pot files"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  rebuild-pots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mtasa
          environment-file: utils/localization/environment.yml
          python-version: 3
          auto-activate-base: false
      - run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends gettext
      - run: python "utils/localization/build_gettext_catalog.py"
        shell: bash -l {0}
      - run: python "utils/localization/build_gettext_catalog_nsi.py"
        shell: bash -l {0}
      - id: stage_changes
        run: |
          git config user.name "Pot Bot"
          git config user.email "github@multitheftauto.com"

          # Check that diff contains something and it's not only POT-Creation-Date
          if [[ $(git diff --unified=0 "Shared/data/MTA San Andreas/MTA/locale/en_US/client.pot" | grep -v POT-Creation-Date | grep '^[+|-][^+|-]') ]]
          then
            git add "Shared/data/MTA San Andreas/MTA/locale/en_US/client.pot" && git commit -m "Update client en_US pot" -m "[ci skip]"
          fi

          # Check that diff contains something and it's not only POT-Creation-Date
          if [[ $(git diff --unified=0 "Shared/installer/locale/en_US.pot" | grep -v POT-Creation-Date | grep '^[+|-][^+|-]') ]]
          then
            git add "Shared/installer/locale/en_US.pot" && git commit -m "Update installer en_US pot" -m "[ci skip]"
          fi

          echo "::echo::on"

          if [[ $(git diff --name-only --staged) ]]
          then
            echo "::set-output name=has_changes::1"
          else
            echo "::set-output name=has_changes::0"
          fi
      - name: Create Pull Request
        if: ${{ steps.stage_changes.outputs.has_changes == '1' }}
        uses: peter-evans/create-pull-request@v4
        with:
          body: |
            It's that time again. I've rebuilt the English pot files.

            Please review and merge these changes at your convenience.
          branch: l10n/update-pots
          delete-branch: true
          labels: |
            localization
          title: Update pot files
