name: 'Sync master to maetro'

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sync-master-to-maetro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_CI_PAT }}

      - id: sync_commits
        name: Sync commits
        run: |
          # GitHub Actions bot user
          git config --global user.name "Maetro Bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout release/maetro
          git merge master --no-ff --no-edit --no-commit || true
          
          # Discard locale conflicts
          git checkout --ours -- Shared/installer/locale "Shared/data/MTA San Andreas/MTA/locale"
          git add --verbose Shared/installer/locale "Shared/data/MTA San Andreas/MTA/locale"
          
          # Discard install_cef.lua conflicts
          git checkout --ours -- utils/buildactions/install_cef.lua
          git add --verbose utils/buildactions/install_cef.lua
          
          # We should be done with the merge now
          printf "Synchronize changes from 1.6 master branch [ci skip]\n\n" > commit.txt
          git log --expand-tabs=4 --pretty=format:'%h %s' release/maetro..master >> commit.txt
          git commit --no-edit --allow-empty -F commit.txt

          git push origin release/maetro
